"""Add modify_date column to MembershipPayment

Revision ID: 00c870f475a0
Revises: 835e11d4ed1d
Create Date: 2024-10-22 23:45:42.006507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c870f475a0'
down_revision = '835e11d4ed1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_payment', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###
