"""empty message

Revision ID: 0a73a0f0a79e
Revises: 2e55d78a1829
Create Date: 2024-08-02 10:36:30.994628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a73a0f0a79e'
down_revision = '2e55d78a1829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.create_table('answer_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'answer_id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('business_status',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('business_item',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('cellphone',
               existing_type=mysql.VARCHAR(length=13),
               nullable=True)

    with op.batch_alter_table('transport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrust_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('con_truck_no', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('entrust_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('entrust_remit_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('entrust_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('entrust_fee_date', sa.Date(), nullable=True))
        batch_op.alter_column('trans_method',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport', schema=None) as batch_op:
        batch_op.alter_column('trans_method',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
        batch_op.drop_column('entrust_fee_date')
        batch_op.drop_column('entrust_fee')
        batch_op.drop_column('entrust_remit_date')
        batch_op.drop_column('entrust_amount')
        batch_op.drop_column('con_truck_no')
        batch_op.drop_column('entrust_date')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('cellphone',
               existing_type=mysql.VARCHAR(length=13),
               nullable=False)
        batch_op.alter_column('business_item',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
        batch_op.alter_column('business_status',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)

    op.drop_table('answer_voter')
    op.drop_table('question_voter')
    op.drop_table('answer')
    op.drop_table('question')
    # ### end Alembic commands ###
