"""empty message

Revision ID: 15e3dca44c2a
Revises: 
Create Date: 2024-07-31 23:45:32.327799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e3dca44c2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.Date(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('truck_name', sa.String(length=16), nullable=True),
    sa.Column('truck_no', sa.String(length=12), nullable=False),
    sa.Column('truck_class', sa.String(length=12), nullable=True),
    sa.Column('truck_ton', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('business_no', sa.String(length=12), nullable=False),
    sa.Column('firm', sa.String(length=32), nullable=False),
    sa.Column('member_name', sa.String(length=16), nullable=False),
    sa.Column('zip', sa.String(length=6), nullable=True),
    sa.Column('address', sa.String(length=56), nullable=True),
    sa.Column('business_status', sa.String(length=16), nullable=False),
    sa.Column('business_item', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('cellphone', sa.String(length=13), nullable=False),
    sa.Column('tel', sa.String(length=12), nullable=True),
    sa.Column('fax', sa.String(length=12), nullable=True),
    sa.Column('bank_name', sa.String(length=24), nullable=True),
    sa.Column('bank_no', sa.String(length=24), nullable=True),
    sa.Column('bank_account', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
