"""empty message

Revision ID: 2e55d78a1829
Revises: 15e3dca44c2a
Create Date: 2024-08-01 16:48:29.894667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e55d78a1829'
down_revision = '15e3dca44c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.Date(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('company_class', sa.String(length=1), nullable=False),
    sa.Column('business_no', sa.String(length=12), nullable=False),
    sa.Column('company', sa.String(length=32), nullable=False),
    sa.Column('president', sa.String(length=16), nullable=False),
    sa.Column('zip', sa.String(length=6), nullable=True),
    sa.Column('address', sa.String(length=56), nullable=True),
    sa.Column('business_status', sa.String(length=16), nullable=False),
    sa.Column('business_item', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('cellphone', sa.String(length=13), nullable=False),
    sa.Column('tel', sa.String(length=12), nullable=True),
    sa.Column('fax', sa.String(length=12), nullable=True),
    sa.Column('bank_name', sa.String(length=24), nullable=True),
    sa.Column('bank_no', sa.String(length=24), nullable=True),
    sa.Column('bank_account', sa.String(length=16), nullable=True),
    sa.Column('note', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_date', sa.Date(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('cost_company', sa.String(length=32), nullable=False),
    sa.Column('cost_class', sa.String(length=1), nullable=False),
    sa.Column('statement', sa.String(length=32), nullable=True),
    sa.Column('payment', sa.String(length=1), nullable=False),
    sa.Column('bank_card', sa.String(length=32), nullable=True),
    sa.Column('cost_amount', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_method', sa.String(length=1), nullable=False),
    sa.Column('trans_class', sa.String(length=1), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('trans_date', sa.Date(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('trans_company', sa.String(length=32), nullable=True),
    sa.Column('consignor', sa.String(length=32), nullable=True),
    sa.Column('load_region', sa.String(length=64), nullable=True),
    sa.Column('load_method', sa.String(length=1), nullable=True),
    sa.Column('load_state', sa.String(length=1), nullable=True),
    sa.Column('unload_date', sa.Date(), nullable=True),
    sa.Column('consignee', sa.String(length=32), nullable=True),
    sa.Column('unload_region', sa.String(length=64), nullable=True),
    sa.Column('unload_method', sa.String(length=1), nullable=True),
    sa.Column('terms', sa.String(length=2), nullable=False),
    sa.Column('trans_amount', sa.Integer(), nullable=False),
    sa.Column('payment', sa.String(length=1), nullable=True),
    sa.Column('trans_set_date', sa.Date(), nullable=True),
    sa.Column('brokerage_fee', sa.Integer(), nullable=True),
    sa.Column('brokerage_date', sa.Date(), nullable=True),
    sa.Column('trans_type', sa.String(length=1), nullable=False),
    sa.Column('comment', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.Date(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('web_site', sa.String(length=32), nullable=True),
    sa.Column('content', sa.String(length=32), nullable=True),
    sa.Column('web_id', sa.String(length=32), nullable=True),
    sa.Column('web_pw', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website')
    op.drop_table('transport')
    op.drop_table('cost')
    op.drop_table('company')
    # ### end Alembic commands ###
