"""empty message

Revision ID: 61336ea1b06e
Revises: 0a73a0f0a79e
Create Date: 2024-08-20 13:22:51.919137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61336ea1b06e'
down_revision = '0a73a0f0a79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('president',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)

    with op.batch_alter_table('transport', schema=None) as batch_op:
        batch_op.drop_column('load_method')
        batch_op.drop_column('order_date')
        batch_op.drop_column('trans_class')
        batch_op.drop_column('trans_method')
        batch_op.drop_column('entrust_fee')
        batch_op.drop_column('entrust_remit_date')
        batch_op.drop_column('con_truck_no')
        batch_op.drop_column('unload_method')
        batch_op.drop_column('load_state')
        batch_op.drop_column('entrust_amount')
        batch_op.drop_column('entrust_date')
        batch_op.drop_column('entrust_fee_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrust_fee_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('entrust_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('entrust_amount', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('load_state', mysql.VARCHAR(length=1), nullable=True))
        batch_op.add_column(sa.Column('unload_method', mysql.VARCHAR(length=1), nullable=True))
        batch_op.add_column(sa.Column('con_truck_no', mysql.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('entrust_remit_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('entrust_fee', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('trans_method', mysql.VARCHAR(length=1), nullable=True))
        batch_op.add_column(sa.Column('trans_class', mysql.VARCHAR(length=1), nullable=False))
        batch_op.add_column(sa.Column('order_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('load_method', mysql.VARCHAR(length=1), nullable=True))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('president',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)

    op.create_table('website',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('register_date', sa.DATE(), nullable=False),
    sa.Column('modify_date', mysql.DATETIME(), nullable=True),
    sa.Column('web_site', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('web_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('web_pw', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
