"""Add annotation column to MembershipPayment

Revision ID: 835e11d4ed1d
Revises: 98eda817f6b6
Create Date: 2024-10-21 19:24:55.368652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835e11d4ed1d'
down_revision = '98eda817f6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annotation', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_payment', schema=None) as batch_op:
        batch_op.drop_column('annotation')

    # ### end Alembic commands ###
