"""empty message

Revision ID: 898510bca43a
Revises: 
Create Date: 2024-10-18 20:34:34.810398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898510bca43a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.Date(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('cancel_date', sa.DateTime(), nullable=True),
    sa.Column('deposit_date', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('truck_name', sa.String(length=16), nullable=True),
    sa.Column('truck_no', sa.String(length=12), nullable=False),
    sa.Column('truck_class', sa.String(length=12), nullable=True),
    sa.Column('truck_ton', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('business_no', sa.String(length=12), nullable=False),
    sa.Column('company', sa.String(length=32), nullable=False),
    sa.Column('member_name', sa.String(length=16), nullable=False),
    sa.Column('zip', sa.String(length=6), nullable=True),
    sa.Column('address', sa.String(length=56), nullable=True),
    sa.Column('business_status', sa.String(length=16), nullable=False),
    sa.Column('business_item', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('cellphone', sa.String(length=13), nullable=False),
    sa.Column('tel', sa.String(length=12), nullable=True),
    sa.Column('fax', sa.String(length=12), nullable=True),
    sa.Column('bank_name', sa.String(length=24), nullable=True),
    sa.Column('bank_no', sa.String(length=24), nullable=True),
    sa.Column('bank_account', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=32), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.Date(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('company_class', sa.String(length=1), nullable=False),
    sa.Column('business_no', sa.String(length=12), nullable=False),
    sa.Column('firm', sa.String(length=32), nullable=False),
    sa.Column('president', sa.String(length=16), nullable=True),
    sa.Column('zip', sa.String(length=6), nullable=True),
    sa.Column('address', sa.String(length=56), nullable=True),
    sa.Column('business_status', sa.String(length=16), nullable=True),
    sa.Column('business_item', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('cellphone', sa.String(length=13), nullable=True),
    sa.Column('tel', sa.String(length=12), nullable=True),
    sa.Column('fax', sa.String(length=12), nullable=True),
    sa.Column('note', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_date', sa.Date(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('cost_company', sa.String(length=32), nullable=False),
    sa.Column('cost_class', sa.String(length=1), nullable=False),
    sa.Column('statement', sa.String(length=32), nullable=True),
    sa.Column('payment', sa.String(length=1), nullable=False),
    sa.Column('bank_card', sa.String(length=32), nullable=True),
    sa.Column('cost_amount', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_date', sa.Date(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('trans_company', sa.String(length=32), nullable=True),
    sa.Column('consignor', sa.String(length=32), nullable=True),
    sa.Column('load_region', sa.String(length=64), nullable=True),
    sa.Column('unload_date', sa.Date(), nullable=True),
    sa.Column('consignee', sa.String(length=32), nullable=True),
    sa.Column('unload_region', sa.String(length=64), nullable=True),
    sa.Column('terms', sa.String(length=2), nullable=False),
    sa.Column('trans_amount', sa.Integer(), nullable=False),
    sa.Column('payment', sa.String(length=1), nullable=True),
    sa.Column('trans_set_date', sa.Date(), nullable=True),
    sa.Column('brokerage_fee', sa.Integer(), nullable=True),
    sa.Column('brokerage_date', sa.Date(), nullable=True),
    sa.Column('trans_type', sa.String(length=1), nullable=False),
    sa.Column('comment', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.create_table('answer_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_voter')
    op.drop_table('question_voter')
    op.drop_table('answer')
    op.drop_table('transport')
    op.drop_table('question')
    op.drop_table('cost')
    op.drop_table('company')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
